### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'swag'

### ISSUE THREAD

**Issue by ced42** [flasgger/flasgger#475]
Hello,

# Describe bug

I would try one of the marshmallow example given in the readme, I have this error:
```
Traceback (most recent call last):
  File "/home/clachat/wd/codes/microservices/test_pytest_flask/src/test_flasgger.py", line 37, in <module>
    def index(body: Body, query: Query, id: int, name: str):
  File "/home/clachat/wd/codes/microservices/test_pytest_flask/.venv/lib/python3.9/site-packages/flask/app.py", line 1315, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/clachat/wd/codes/microservices/test_pytest_flask/.venv/lib/python3.9/site-packages/flask/app.py", line 98, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/clachat/wd/codes/microservices/test_pytest_flask/.venv/lib/python3.9/site-packages/flask/app.py", line 1275, in add_url_rule
    rule = self.url_rule_class(rule, methods=methods, **options)
TypeError: __init__() got an unexpected keyword argument 'swag'
```

# How to reproduce the bug
The code of the example is:
```
from flask import Flask, jsonify
from flasgger import Swagger, SwaggerView, Schema, fields


class Color(Schema):
    name = fields.Str()

class Palette(Schema):
    pallete_name = fields.Str()
    colors = fields.Nested(Color, many=True)

class PaletteView(SwaggerView):
    parameters = [
        {
            "name": "palette",
            "in": "path",
            "type": "string",
            "enum": ["all", "rgb", "cmyk"],
            "required": True,
            "default": "all"
        }
    ]
    responses = {
        200: {
            "description": "A list of colors (may be filtered by palette)",
            "schema": Palette
        }
    }

    def get(self, palette):
        """
        Colors API using schema
        This example is using marshmallow schemas
        """
        all_colors = {
            'cmyk': ['cian', 'magenta', 'yellow', 'black'],
            'rgb': ['red', 'green', 'blue']
        }
        if palette == 'all':
            result = all_colors
        else:
            result = {palette: all_colors.get(palette)}
        return jsonify(result)

app = Flask(__name__)
swagger = Swagger(app)

app.add_url_rule(
    '/colors/<palette>',
    view_func=PaletteView.as_view('colors'),
    methods=['GET']
)

app.run(debug=True)
```

# Environment
I have the following versions:
- python: 3.9.2
- apispec: 4.4.0
- flasgger: 0.9.5
- flask: 1.1.2
- marshmallow: 3.11.1
- setuptools: 56.1.0

**Comment by mgjeffries** [comment]
I have this issue too

**Comment by ced42** [comment]
With the main branch, the bug isn't there anymore
