### ISSUE TITLE
cant use external file

### ISSUE THREAD

**Issue by tommyjcarpenter** [flasgger/flasgger#482]
I am getting the exception `AttributeError: 'dict' object has no attribute 'startswith'` despite passing a string:

```
file_dir = path.dirname(path.abspath(__file__))
schema_path = path.join(file_dir, "openapi.yaml")
schema = Path(schema_path)


@app.route("/ingestion-job", methods=["GET", "POST"])
@swag_from(schema, endpoint="ingestion-job", methods=["POST"], validation=True)
def ingestion_root():
    if request.method == "POST":
        manifest = request.json

...
```

Leads to:
```
[2021-05-24 09:21:50,640] [dataapi.def_controller] [DEBUG   ] Rebuilding cache from git using profile: None
[2021-05-24 09:21:50,652] [dataapi.def_controller] [DEBUG   ] Cached 1 ingestion jobs
[2021-05-24 09:21:50,895] [dataapi.app ] [ERROR   ] Exception on /ingestion-job [POST]
Traceback (most recent call last):
  File "/Users/tommycarpenter/Development/python-data-ingestion-api/.tox/py39/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tommycarpenter/Development/python-data-ingestion-api/.tox/py39/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/tommycarpenter/Development/python-data-ingestion-api/.tox/py39/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/tommycarpenter/Development/python-data-ingestion-api/.tox/py39/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/tommycarpenter/Development/python-data-ingestion-api/.tox/py39/lib/python3.9/site-packages/flasgger/utils.py", line 266, in wrapper
    validate(
  File "/Users/tommycarpenter/Development/python-data-ingestion-api/.tox/py39/lib/python3.9/site-packages/flasgger/utils.py", line 382, in validate
    if not filepath.startswith('/'):
AttributeError: 'dict' object has no attribute 'startswith'
```

**Comment by ischyron** [comment]
flasgger==0.9.5
Python 3.9.5

same issue with this usage:-
```python
from flasgger import Swagger
....
swagger = Swagger(app)
```
specs.yaml is in local and declaration goes like this
```python
                def get(self, x):
                """
		file: specs.yaml
		"""
```

Error
```
  File "/usr/local/lib/python3.9/site-packages/flasgger/utils.py", line 546, in load_from_file
    enc = detect_by_bom(swag_path)
  File "/usr/local/lib/python3.9/site-packages/flasgger/utils.py", line 575, in detect_by_bom
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.9/site-packages/flask_restful/specs.yaml'
```

**Comment by robertlugg** [comment]
Same problem as reported by OP. 

This a bug with flasgger if my analysis below is correct.

The problem is happening in `utils.py/validate`.  'filepath' is of different type depending on the KWarguments to `@swag_from()`.  If you specify `validate=True` AND `methods` **specified at all**, then this will fail.  'filepath' comes in as a dict:
example:
```
{'put': '/u/itsme/a/b/c/web_server/swagger.yml'}
```
if `methods` kwarg is not specified, then `filepath` comes in as a string.

 I believe @ischyron is reporting a different issue.
