### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory from installed .egg

### ISSUE THREAD

**Issue by aalonzolu** [flasgger/flasgger#488]
I'm using setuptools to install my package but it seems that flasgger has an error loading the yml files from the .egg.

This is the error:
```
MyApp.main:Exception on /swagger.json [GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/flasgger/utils.py", line 546, in load_from_file
enc = detect_by_bom(swag_path)
File "/usr/local/lib/python3.7/site-packages/flasgger/utils.py", line 575, in detect_by_bom
with open(path, 'rb') as f:
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/lib/python3.7/site-packages/MyApp-1.0.0-py3.7.egg/MyApp/api/definition.yml'
```

In setup I have declared this and when I unzip the .egg the yml files are there.
```
package_data={
        "MyApp": ["*/*.yml", "*/*/*.yml"],
    },
```

For my endpoints, I'm using `@swag_from('definition.yml')`

**Comment by ejewett-23andme** [comment]
Was this issue resolved? I'm having a similar problem. It would be great to know what fixed if for you.

**Comment by ejewett-23andme** [comment]
Running "pip install ." rather than "python setup.py install" resolved the problem for me.
