### ISSUE TITLE
Swagger config

### ISSUE THREAD

**Issue by tyki6** [flasgger/flasgger#489]
I want to change only url path for swagger ui.
When i try to send minimal config i got an error([cf: stack trace](#stack-trace)).For running a valid config specs, static_url_path, headers are mandatory.Can you create an enhancement that get basic param if specs or static_url_path aren't here?
# Description
## Code
```python
config = {
     "specs_route": "/swagger/"
}
swagger = Swagger(app, config=config)
```
## Stack Trace
```python
Traceback (most recent call last):
  File "/home/matthieu/PycharmProjects/lmfr-datatech-mobilitytech-clean-ws1/apps.py", line 18, in <module>
    swagger = Swagger(app, config=config)
  File "/home/matthieu/PycharmProjects/venv/lmfr-datatech-mobilitytech-clean-ws1/lib/python3.8/site-packages/flasgger/base.py", line 217, in __init__
    self.init_app(app)
  File "/home/matthieu/PycharmProjects/venv/lmfr-datatech-mobilitytech-clean-ws1/lib/python3.8/site-packages/flasgger/base.py", line 230, in init_app
    self.register_views(app)
  File "/home/matthieu/PycharmProjects/venv/lmfr-datatech-mobilitytech-clean-ws1/lib/python3.8/site-packages/flasgger/base.py", line 601, in register_views
    for spec in self.config['specs']:
KeyError: 'specs'
```
# Possible enhancement
```python
basic_specs = [
            {
                "endpoint": 'apispec_1',
                "route": '/apispec_1.json',
                "rule_filter": lambda rule: True,  # all in
                "model_filter": lambda tag: True,  # all in
            }
        ]
for spec in self.config.get('specs', basic_specs):
    self.endpoints.append(spec['endpoint'])
    blueprint.add_url_rule(
        spec['route'],
        spec['endpoint'],
        view_func=wrap_view(APISpecsView.as_view(
            spec['endpoint'],
            loader=partial(
                self.get_apispecs, endpoint=spec['endpoint'])
        ))
    )

app.register_blueprint(blueprint)
```
# Informations
- OS VERSION: `Ubuntu 18.04.5 LTS`
- PYTHON VERSION: `3.8.11`
- FLASGER VERSION: `0.9.5`

**Comment by amauryval** [comment]
Try this (vers 0.9.5) :

```Python
config = {
     "specs_route": "/my/amazing/url_doc"
}
# set merge to True
swagger = Swagger(app, config=config, merge=True)
```
