### ISSUE TITLE
Creating a functional EXE with flasgger via pyinstaller?

### ISSUE THREAD

**Issue by GiladPachter** [flasgger/flasgger#522]
Hi,

I have a skeleton RESTful Swagger project that combines **Flask**, **Flask-RESTful** and **flasgger**.
[](https://github.com/flasgger/flasgger/blob/master/examples/restful.py)
[](https://github.com/flasgger/flasgger/blob/master/examples/username_specs.yml)

It works great as python script.
I want to turn it into a single EXE using pyinstaller.
It turns out that the SWAGGER web page doesn't load correctly when the EXE runs my REST service.
(details below)

Is there any way to put it all together?

Thanks in advance.

### **ERROR Details:**

Traceback (most recent call last):
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\app.py", line 2091, in __call__
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\app.py", line 2076, in wsgi_app
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask_restful\__init__.py", line 271, in error_router
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\app.py", line 2073, in wsgi_app
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\app.py", line 1518, in full_dispatch_request
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask_restful\__init__.py", line 271, in error_router
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\app.py", line 1516, in full_dispatch_request
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\app.py", line 1502, in dispatch_request
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\views.py", line 84, in view
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\views.py", line 158, in dispatch_request
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flasgger\base.py", line 115, in get
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\templating.py", line 148, in render_template
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\jinja2\environment.py", line 1068, in get_or_select_template
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\jinja2\environment.py", line 997, in get_template
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\jinja2\environment.py", line 958, in _load_template
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\jinja2\loaders.py", line 125, in load
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\templating.py", line 59, in get_source
    
  File "C:\Users\user1\AppData\Local\Temp\_MEI13402\flask\templating.py", line 95, in _get_source_fast
    
jinja2.exceptions.TemplateNotFound: flasgger/index.html

**Comment by onuratakan** [comment]
I fix the templatest but ı need help about flasgger static mechanism.

```
# -*- mode: python ; coding: utf-8 -*-

import flasgger

from os.path import dirname, abspath, join, basename

block_cipher = None

flasgger_templates = join(flasgger.__path__[0], "ui2", "templates")
flasgger_statics = join(flasgger.__path__[0], "ui2", "static")

a = Analysis(
    ['decentra_network/api/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        (flasgger_templates, join("templates")),
        (flasgger_statics, join("flasgger_static")),
        ],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Decentra-Network-API',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(exe,
               Tree('.'),
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               upx=True,
               upx_exclude=[],
               name='Decentra-Network-API')

```

**Comment by dcoutinho1328** [comment]
Try adding "--collect-all flasgger" to your pyinstaller cmd. It should work

**Comment by onuratakan** [comment]
> Try adding "--collect-all flasgger" to your pyinstaller cmd. It should work

I will try and if its work i will open a pr for this information

**Comment by tychen6677** [comment]
> Try adding "--collect-all flasgger" to your pyinstaller cmd. It should work

It works. thanks
